import "./globals.css";
import Providers from "./Components/provider";
import { Toaster } from "sonner";
import { helveticaNowDisplay } from "@/public/Font/fontTypeWeight";

export const metadata = {
  title: "Bridge Asset Management",
  description: "Generated by Aretex",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${helveticaNowDisplay.className} text-base`}>
        <Providers>
          {children}
          <Toaster richColors />
        </Providers>
      </body>
    </html>
  );
}
